{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol","variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"role":"symbol","title":"AuthenticationError.failure(_:)","modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"title":"AuthenticationError.failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic"},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","type":"image","variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/vigramsdk","images":[{"identifier":"logo.png","type":"icon"}],"role":"collection","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","title":"VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","role":"symbol","title":"AuthenticationError","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror","abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}]}}}