{"seeAlsoSections":[{"title":"Errors","generated":true,"identifiers":["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripServiceError","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/PeripheralError"],"anchor":"Errors"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/badMeasurement(_:)","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/measurementCancelled","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/measurementFailure"],"title":"Enumeration Cases"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/Error-Implementations","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/LocalizedError-Implementations"],"anchor":"Default-Implementations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/singlepointrecordingerror"]}],"abstract":[{"text":"SinglePointRecordingError are thrown, when due to the filtering phase of single point recordings there is not enough valid data to create a singlePoint.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK"]]},"metadata":{"modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK25SinglePointRecordingErrorO","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SinglePointRecordingError"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SinglePointRecordingError"}],"role":"symbol","title":"SinglePointRecordingError","roleHeading":"Enumeration"},"relationshipsSections":[{"identifiers":["doc:\/\/com.vigram.VigramSDK\/10Foundation14LocalizedErrorP","doc:\/\/com.vigram.VigramSDK\/s8CopyableP","doc:\/\/com.vigram.VigramSDK\/s5ErrorP","doc:\/\/com.vigram.VigramSDK\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SinglePointRecordingError"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"To investigate possible issues with the measurement, have a look at the provided associated data.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError/measurementFailure":{"url":"\/documentation\/vigramsdk\/singlepointrecordingerror\/measurementfailure","role":"symbol","kind":"symbol","title":"SinglePointRecordingError.measurementFailure","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"measurementFailure","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/measurementFailure","abstract":[{"text":"The measurement failure.","type":"text"}],"type":"topic"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothService":{"navigatorTitle":[{"text":"BluetoothService","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","abstract":[{"type":"text","text":"A BluetoothService is used to handle bluetooth connections."}],"role":"symbol","url":"\/documentation\/vigramsdk\/bluetoothservice","kind":"symbol","type":"topic","title":"BluetoothService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"BluetoothService","kind":"identifier"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/PeripheralError":{"navigatorTitle":[{"text":"PeripheralError","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/peripheralerror","abstract":[{"text":"PeripheralError combines different failure events that can be emitted on sending data to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/Peripheral","type":"reference"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/PeripheralError","title":"PeripheralError"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError":{"url":"\/documentation\/vigramsdk\/singlepointrecordingerror","navigatorTitle":[{"text":"SinglePointRecordingError","kind":"identifier"}],"title":"SinglePointRecordingError","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError","abstract":[{"text":"SinglePointRecordingError are thrown, when due to the filtering phase of single point recordings there is not enough valid data to create a singlePoint.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SinglePointRecordingError","kind":"identifier"}],"type":"topic"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripTaskError":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NtripTaskError"}],"navigatorTitle":[{"text":"NtripTaskError","kind":"identifier"}],"title":"NtripTaskError","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError","abstract":[{"text":"NtripTaskError lists different errors that can be emitted by ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTask","type":"reference"},{"text":" implementations.","type":"text"}],"url":"\/documentation\/vigramsdk\/ntriptaskerror"},"doc://com.vigram.VigramSDK/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.vigram.VigramSDK\/10Foundation14LocalizedErrorP"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripServiceError":{"navigatorTitle":[{"kind":"identifier","text":"NtripServiceError"}],"abstract":[{"type":"text","text":"NtripServiceError contains custom failure events when connecting to Ntrip services."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NtripServiceError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripServiceError","type":"topic","role":"symbol","title":"NtripServiceError","url":"\/documentation\/vigramsdk\/ntripserviceerror","kind":"symbol"},"doc://com.vigram.VigramSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.vigram.VigramSDK\/s8SendableP"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/Peripheral":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Peripheral","kind":"identifier"}],"abstract":[{"type":"text","text":"Peripheral provides a write and receive interface to communicate with the viDoc device."}],"type":"topic","url":"\/documentation\/vigramsdk\/peripheral","navigatorTitle":[{"text":"Peripheral","kind":"identifier"}],"kind":"symbol","title":"Peripheral","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/Peripheral","role":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError/Error-Implementations":{"abstract":[],"url":"\/documentation\/vigramsdk\/singlepointrecordingerror\/error-implementations","title":"Error Implementations","kind":"article","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/Error-Implementations","type":"topic","role":"collectionGroup"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError/measurementCancelled":{"title":"SinglePointRecordingError.measurementCancelled","url":"\/documentation\/vigramsdk\/singlepointrecordingerror\/measurementcancelled","abstract":[{"type":"text","text":"The measurement cancelled by user."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"measurementCancelled","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/measurementCancelled","kind":"symbol"},"logo.png":{"type":"image","identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"alt":"Vigram logo."},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError":{"url":"\/documentation\/vigramsdk\/bluetoothserviceerror","role":"symbol","kind":"symbol","title":"BluetoothServiceError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BluetoothServiceError","kind":"identifier"}],"navigatorTitle":[{"text":"BluetoothServiceError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError","abstract":[{"type":"text","text":"BluetoothServiceError lists different errors that can be propagated by "},{"isActive":true,"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","type":"reference"},{"text":" implementations.","type":"text"}],"type":"topic"},"doc://com.vigram.VigramSDK/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.vigram.VigramSDK\/s8CopyableP"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"type":"topic","url":"\/documentation\/vigramsdk","abstract":[],"kind":"symbol","title":"VigramSDK","role":"collection","images":[{"identifier":"logo.png","type":"icon"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripTask":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NtripTask","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NtripTask"}],"abstract":[{"text":"A NtripTask requests RTK data over a NTRIP connection.","type":"text"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTask","title":"NtripTask","url":"\/documentation\/vigramsdk\/ntriptask"},"doc://com.vigram.VigramSDK/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.vigram.VigramSDK\/s5ErrorP"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError/LocalizedError-Implementations":{"abstract":[],"title":"LocalizedError Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/LocalizedError-Implementations","url":"\/documentation\/vigramsdk\/singlepointrecordingerror\/localizederror-implementations","type":"topic"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/SinglePointRecordingError/badMeasurement(_:)":{"type":"topic","role":"symbol","title":"SinglePointRecordingError.badMeasurement(_:)","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/SinglePointRecordingError\/badMeasurement(_:)","abstract":[{"type":"text","text":"The measurement failed due to too much filtered, non-valid data."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"badMeasurement"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:9VigramSDK15EnvironmentDataV","text":"EnvironmentData"},{"text":"])","kind":"text"}],"url":"\/documentation\/vigramsdk\/singlepointrecordingerror\/badmeasurement(_:)","kind":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"type":"topic","role":"symbol","kind":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"url":"\/documentation\/vigramsdk\/authenticationerror"}}}