{"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/LocalizedError-Implementations"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription","interfaceLanguage":"swift"},"metadata":{"externalID":"s:9VigramSDK19AuthenticationErrorO16errorDescriptionSSSgvp","modules":[{"name":"VigramSDK"}],"title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"extendedModule":"VigramSDK","role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/errorDescription":{"title":"errorDescription","kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/vigramsdk\/authenticationerror\/errordescription","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"kind":"symbol","type":"topic","role":"symbol","title":"AuthenticationError","url":"\/documentation\/vigramsdk\/authenticationerror"},"logo.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"identifier":"logo.png","alt":"Vigram logo."},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/LocalizedError-Implementations":{"url":"\/documentation\/vigramsdk\/authenticationerror\/localizederror-implementations","abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/LocalizedError-Implementations","type":"topic","kind":"article","role":"collectionGroup","title":"LocalizedError Implementations"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/vigramsdk","role":"collection","title":"VigramSDK","images":[{"type":"icon","identifier":"logo.png"}]}}}