{"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"metadata":{"symbolKind":"case","modules":[{"name":"VigramSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Case","title":"AuthenticationError.failure(_:)","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","role":"collection","title":"VigramSDK","type":"topic","images":[{"identifier":"logo.png","type":"icon"}],"url":"\/documentation\/vigramsdk","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","abstract":[]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","title":"AuthenticationError","kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror","role":"symbol"},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"AuthenticationError.failure(_:)"}}}