{"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","title":"AuthenticationError.failure(_:)","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"VigramSDK"}]},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"title":"AuthenticationError","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/authenticationerror"},"logo.png":{"identifier":"logo.png","alt":"Vigram logo.","type":"image","variants":[{"url":"\/images\/com.vigram.VigramSDK\/logo.png","traits":["1x","light"]}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"type":"topic","title":"AuthenticationError.failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","role":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"images":[{"type":"icon","identifier":"logo.png"}],"role":"collection","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","url":"\/documentation\/vigramsdk","abstract":[],"type":"topic","kind":"symbol","title":"VigramSDK"}}}